#pragma once

#define BASE_BEGIN_NAMESPACE(ns) namespace ns {
#define BASE_BEGIN_ANONYMOUS_NAMESPACE namespace {

#define _BASE_END_NAMESPACE }
#define BASE_END_NAMESPACE(ns) _BASE_END_NAMESPACE
#define BASE_END_ANONYMOUS_NAMESPACE _BASE_END_NAMESPACE

#define BASE_NS_BEGIN BASE_BEGIN_NAMESPACE(base)
#define BASE_NS_END BASE_END_NAMESPACE(base)
#define BASE_NS_PREFIX ::base
